# Run (from repository root):
#   docker compose -f .docker/compose.dev.yaml --env-file .env up --build

services:
  valhalla:
    image: hackathon-valhalla
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile.valhalla
    env_file:
      - ../.env
    networks:
      - internal
      - default
    ports:
      - 127.0.0.1:8002:8002
    environment:
      - server_threads=2  # determines how many threads will be used to run the valhalla server
      - serve_tiles=True  # If True, starts the service. If false, stops after building the graph.
      - use_tiles_ignore_pbf=True  # load existing valhalla_tiles.tar directly
      - tileset_name=2  # name of the resulting graph on disk
      - build_elevation=False  # build elevation with "True" or "Force": will download only the elevation for areas covered by the graph tiles
      - build_admins=False  # build admins db with "True" or "Force"
      - build_time_zones=False  # build timezone db with "True" or "Force"
      - build_transit=False  # build transit, needs existing GTFS directories mapped to /gtfs_feeds
      - build_tar=True  # build an indexed tar file from the tile_dir for faster graph loading times
      - force_rebuild=False  # forces a rebuild of the routing tiles with "True"
      - update_existing_config=True  # if there are new config entries in the default config, add them to the existing config  
    volumes:
      - ${VALHALLA_PERSISTENT_DIR_LOCAL}:/data

  # database:
  #   image: postgres:14.22
  #   env_file:
  #     - ../.env
  # #   environment:
  # #     - POSTGRES_USER=${POSTGRES_USER}
  # #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  # #     - POSTGRES_DB=${POSTGRES_DB}
  #   networks:
  #     - internal
  #   volumes:
  #     - ${POSTGRES_PERSISTENT_DIR_LOCAL}:/var/lib/postgresql/data

  back:
    image: hackathon-back
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile.back
    env_file:
      - ../.env
    volumes:
      - ${FUEL_PRICE_CSV_PATH}:/data
    networks:
      - internal
    # TEMP

      - default
    ports:
      - 127.0.0.1:5000:8080
    
    # END TEMP
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - valhalla
      # - database

  front:
    image: hackathon-front
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile.front
    env_file:
      - ../.env
    ports:
      - 127.0.0.1:${FRONTEND_PORT}:80
    networks:
      - default
      - internal
    depends_on:
      - back

  # fuel-prices:
  #   image: python:3.11-alpine
  #   command: sh -c "echo '0 0 * * * /usr/local/bin/python /data/scrape_fuel_prices.py' > /var/spool/cron/crontabs/root && crond -f -l 2"
  #   volumes:
  #     - ${FUEL_PRICE_CSV_PATH}:/data
  #   # networks:
  #   #   - internal
  #   #   - default

networks:
  internal:
    internal: true