# Build (from repository root):
#   docker build -f .docker/Dockerfile.front . -t hackathon-front

# Run:
#   docker run -p 127.0.0.1:80:80 hackathon-front

FROM nginx:alpine
COPY ./frontend/ /usr/share/nginx/html/
EXPOSE 80