# Build (from repository root):
#   docker build -f .docker/Dockerfile.back . -t hackathon-back

# Run:
#   docker run -p 127.0.0.1:8080:8080 hackathon-back

# Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY backend/Web/Web.csproj backend/Web/
COPY backend/ ./backend/

RUN dotnet restore backend/Web/Web.csproj
RUN dotnet publish backend/Web/Web.csproj -c Release -o /app/publish --no-restore


# Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "Web.dll"]